INSERT INTO `items` (`name`, `label`, `limit`) VALUES
	('carrot', 'Carrot Stick', 25),
    ('apple', 'Apple', 25),
    ('applepie', 'Apple Pie', 10),
    ('peach', 'Peach', 25),
    ('peachcobbler', 'Peach Cobbler', 10),
    ('banana', 'Banana', 25),
    ('watermelon', 'Watermelon', 25),
    ('vanillaice', 'Vanilla Ice Cream', 25),
    ('chocalateice', 'Choclate Ice Cream', 25),
    ('strawberryice', 'Strawberry Ice Cream', 25),
    ('cottoncandy', 'Cotton Candy', 25),
    ('tvdinner', 'Tv Dinner ', 25),
    ('steak', 'Steak', 25),
    ('cake', 'cake', 1),
    ('rawsteak', 'Raw Steak', 25),
    ('rawchicken', 'Raw Chicken', 25),
    ('friedchicken', 'Fried Chicken', 25),
    ('bakedchicken', 'Baked Chicken', 25),
    ('bacon', 'Bacon', 25),
    ('sausage', 'Sausage', 25),
    ('weedbread', 'Edibles Bread', 25),
    ('weedchicken', 'Edibles Chicken', 25),
    ('weedbrownie', 'Edibles Brownie', 25),
	('salad', 'Ceasar Salad', 25),
    ('applejuice', 'Apple Juice', 25),
    ('grapejuice', 'Grape Juice', 25),
    ('gingerale', 'Canada Dry', 25),
    ('orangesunkist', 'Orange Sunkist', 25),
    ('pepsi', 'Pepsi', 25),
    ('koolaid', 'Kool-Aid', 25),
    ('winecoolers', 'Winecooler', 25),
    ('fireball', 'Fireball', 25),
    ('vacationlifespeacaltydrink', 'VlifeDrink', 25),
    ('springwater', 'Spring Aqua', 25),
    ('yolowater', 'Yolo Water', 25),
    ('gatoraid', 'Gatoraid', 25),
    ('armourdrink', 'Armour Drink Vest', 25),
    ('chocmilk', 'Choo Choo Milk Vest', 25),
    ('SmallArmour', 'Small Armour Vest', 1),
    ('MedArmour', 'Med Armour Vest', 1),
    ('InvincibleArmour', 'Invincible Armour Vest', 1),
    ('CrazyArmour', 'Crazy Armour Vest', 1),
    ('LightAmmo', 'Light Ammo Pack', 25),
    ('SmallAmmo', 'Small Ammo Pack', 25),
    ('BigAmmo', 'Big Ammo Pack', 25),
    ('HeavyAmmo', 'Heavy Ammo Pack', 25)
    ;